### ISSUE TITLE
Responsive design support

### ISSUE THREAD

**Issue by rstefko** [leonardomarino/duo_auth#1]
With Roundcube 1.4.0 we can finally use Roundcube on mobile phones. When I login, the DUO login dialog does not fit the screen, so it is hard to click the buttons.

**Comment by leonardomarino** [comment]
Hi @rstefko thanks for the feedback. I just created a new release that should be mobile friendly and have tested it using my phone with both Chrome and Firefox. Please give it a try and let me know so I can close this.

**Comment by rstefko** [comment]
Hi @leonardomarino. I fount out that I used version 1.0.4.
After the upgrade I have problems with the duosecurity api. Composer installs it, but PHP fails during include:

> PHP Fatal error:  require_once(): Failed opening required 'Client.php'

Do you know what is the problem?

**Comment by leonardomarino** [comment]
Hi @rstefko, that is something that I need to improve during the installation process. You have to create symbolic links from the `plugins/duo_auth` directory

as follows:

`ln -s ../../vendor/duosecurity/duo_api_php/src/* .`

make sure you update your `config.inc.php` file as it will be overwritten too.

**Comment by rstefko** [comment]
Thanks. Seems good on mobile.
