### ISSUE TITLE
Upgrade from 1.0.4 to 1.0.5

### ISSUE THREAD

**Issue by linkp** [leonardomarino/duo_auth#2]
When I view the "About" dialog in my Roundcube installation it reports duo_auth version 1.0.4 is installed.

composer update suggests that everything is up to date

How do I upgrade to the current version of duo_auth?

**Comment by leonardomarino** [comment]
Hi @linkp please run composer as the Web user in the top directory where you have Roundcube installed. Something like this:

```
sudo -u www-data composer require lmr/duo_auth
Using version ^1.0 for lmr/duo_auth
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 0 installs, 1 update, 0 removals
  - Updating lmr/duo_auth (v1.0.5 => v1.0.6): Downloading (100%)         
Writing lock file
Generating autoload files
```

**Comment by linkp** [comment]
I use php-fpm, so user www-data has read-only permissions in that directory. That's not a big deal though, since I can run in the context of the user that owns that directory tree.

Attempts to execute composer return "zsh: command not found: composer" This also does not surprise me as I have always used ./composer.phar to call composer.

Running ./composer.phar require lmr/duo_auth returns the following:

```
user@host roundcubemail $ ./composer.phar require lmr/duo_auth
Using version ^1.0 for lmr/duo_auth                            
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                  
Nothing to install or update
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
```

**Comment by leonardomarino** [comment]
Is it possible for you yo download the release and install it directly? I have updated the repository to include a mobile friendly interface. Sometimes it takes composer a while to recognize the new release.

**Comment by linkp** [comment]
The core of the problem appears to begin with duo_auth > v1.0.4 requiring duosecurity/duo_api_php

When I ran composer require duosecurity/duo_api_php, duo_auth still didn't upgrade since duosecurity/duo_api_php wasn't using dev-master.

I updated the roundcube composer.json to use dev-master instead of ^1.0 and composer update then replaced duosecurity/duo_api_php (1.0.1) with duosecurity/duo_api_php (dev-master e12a636)

That initially broke my Roundcube until I ran the symbolic links requested on the GitHub releases page, at which point Roundcube worked again, but there was no Duo authentication.  Apparently the update from duo_auth v1.0.4 to v1.0.6 removed the config.inc.php.

I replaced it with the config.inc.php from my backup of duo_auth v1.0.4 and everything is working again. Hopefully future updates to duo_auth won't wipe out the symbolic links or the config.inc.php.

**Comment by leonardomarino** [comment]
Hi @linkp I need help to improve these issues. Do you know someone who could contribute to improve the project? I think that a couple of scripts at the pre installation and post installation level would be great.

**Comment by leonardomarino** [comment]
Hi @linkp, I just found out that one needs to execute:

`composer dumpautoload -o` right after `composer require lmr/duo_auth`

This command will recreate a list of autoloaded classes that the plugin needs. I am still investigating how I can keep the `config.inc.php` file if it is existing in the plugin directory.

**Comment by linkp** [comment]
> Hi @linkp I need help to improve these issues. Do you know someone who could contribute to improve the project? I think that a couple of scripts at the pre installation and post installation level would be great.

I might be able to help, depending on what is needed and the time and other requirements involved. I am using this project on my own Roundcube installation, so I have an interest in it continuing to run well.
